char shader_vert[] = "uniform sampler2D defaultTex;\n"
                     "varying float height;\n"
                     "\n"
                     "void main()\n"
                     "{\n"
                     "    vec2 uv = gl_MultiTexCoord0.xy;\n"
                     "    vec4 color = texture2D(defaultTex, uv);\n"
                     "    height = 0.3*color.x + 0.59*color.y + 0.11*color.z;\n"
                     "\n"
                     "    vec4 pos = gl_Vertex;\n"
                     "    pos.z = pos.z + 100.0*height;\n"
                     "    gl_Position = gl_ModelViewProjectionMatrix * pos;\n"
                     "}\n"
                     "\n";
