FROM ubuntu:22.04
LABEL Description="CppJenkinsDockerExample build environment"

RUN apt update
RUN apt install -y git build-essential cmake libboost-all-dev googletest googletest-tools lcov libgtest-dev

                

