char shader_frag[] = "uniform sampler2D cTex;\n"
                     "uniform sampler2D nTex;\n"
                     "varying vec3 lightDir;\n"
                     "\n"
                     "void main()\n"
                     "{\n"
                     "    vec4 base = texture2D( cTex, gl_TexCoord[0].xy );\n"
                     "    vec3 bump = texture2D( nTex, gl_TexCoord[0].xy ).xyz;\n"
                     "\n"
                     "    bump = normalize( bump * 2.0 - 1.0 );\n"
                     "\n"
                     "    float lambert = max( dot( bump, lightDir ), 0.0 );\n"
                     "\n"
                     "    if ( lambert > 0.0 )\n"
                     "    {\n"
                     "        gl_FragColor = base * gl_LightSource[0].diffuse * lambert;\n"
                     "        gl_FragColor += gl_LightSource[0].specular * pow( lambert, 2.0 );\n"
                     "    }\n"
                     "\n"
                     "    gl_FragColor += gl_LightSource[0].ambient;\n"
                     "}\n"
                     "\n";
