#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

################################################################################

function printExecutionTime()
{
    TIME_1=$(date +%s)
    TIME_T=$(expr $TIME_1 - $2 )
    TIME_H=$(expr $TIME_T / 3600 )
    TIME_M=$(expr $(expr $TIME_T - 3600 \* $TIME_H ) / 60 )
    TIME_S=$(expr $TIME_T - 3600 \* $TIME_H - 60 \* $TIME_M )
    TIME_F=`printf %02d ${TIME_H}`:`printf %02d ${TIME_M}`:`printf %02d ${TIME_S}`
    echo "$1 $TIME_F $3 $4"
}

################################################################################

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

################################################################################

TIME_0=$(date +%s)
echo $(date +%Y-%m-%d\ %H:%M:%S) - Computations started

################################################################################
# EXECUTION - START
################################################################################

touch open.foam

echo "Running surfaceFeatureEdges"
TMP_0=$(date +%s)
mkdir surfaceMeshes
surfaceFeatureEdges geometry/geometry.stl surfaceMeshes/geometry.fms -angle 60 > log.surfaceFeatureEdges 2>&1
EXIT_CODE=$?
printExecutionTime "surfaceFeatureEdges finished in " $TMP_0 "with exit code" $EXIT_CODE
if [ $EXIT_CODE -ne 0 ]; then exit $EXIT_CODE; fi

echo "Running cartesianMesh"
TMP_0=$(date +%s)
cartesianMesh > log.cartesianMesh 2>&1
EXIT_CODE=$?
printExecutionTime "cartesianMesh finished in " $TMP_0 "with exit code" $EXIT_CODE
if [ $EXIT_CODE -ne 0 ]; then exit $EXIT_CODE; fi

# echo "Running checkMesh"
# TMP_0=$(date +%s)
# checkMesh > log.checkMesh 2>&1
# EXIT_CODE=$?
# printExecutionTime "checkMesh finished in " $TMP_0 "with exit code" $EXIT_CODE
# if [ $EXIT_CODE -ne 0 ]; then exit $EXIT_CODE; fi

################################################################################
# EXECUTION - FINISH
################################################################################

printExecutionTime "OpenFOAM finished in " $TIME_0
