char shader_vert[] = "uniform float osg_FrameTime;\n"
                     "varying vec4 projCoords;\n"
                     "varying vec3 lightDir, eyeDir;\n"
                     "varying vec2 flowCoords, rippleCoords;\n"
                     "\n"
                     "void main()\n"
                     "{\n"
                     "   vec3 T = vec3(0.0, 1.0, 0.0);\n"
                     "   vec3 N = vec3(0.0, 0.0, 1.0);\n"
                     "   vec3 B = vec3(1.0, 0.0, 0.0);\n"
                     "   T = normalize(gl_NormalMatrix * T);\n"
                     "   B = normalize(gl_NormalMatrix * B);\n"
                     "   N = normalize(gl_NormalMatrix * N);\n"
                     "\n"
                     "   mat3 TBNmat;\n"
                     "   TBNmat[0][0] = T[0]; TBNmat[1][0] = T[1]; TBNmat[2][0] = T[2];\n"
                     "   TBNmat[0][1] = B[0]; TBNmat[1][1] = B[1]; TBNmat[2][1] = B[2];\n"
                     "   TBNmat[0][2] = N[0]; TBNmat[1][2] = N[1]; TBNmat[2][2] = N[2];\n"
                     "\n"
                     "   vec3 vertexInEye = vec3(gl_ModelViewMatrix * gl_Vertex);\n"
                     "   lightDir =  gl_LightSource[0].position.xyz - vertexInEye;\n"
                     "   lightDir = normalize(TBNmat * lightDir);\n"
                     "   eyeDir = normalize(TBNmat * (-vertexInEye));\n"
                     "\n"
                     "   vec2 t1 = vec2(osg_FrameTime*0.02, osg_FrameTime*0.02);\n"
                     "   vec2 t2 = vec2(osg_FrameTime*0.05, osg_FrameTime*0.05);\n"
                     "   flowCoords = gl_MultiTexCoord0.xy * 5.0 + t1;\n"
                     "   rippleCoords = gl_MultiTexCoord0.xy * 10.0 + t2;\n"
                     "\n"
                     "   gl_TexCoord[0] = gl_MultiTexCoord0;\n"
                     "   gl_Position = ftransform();\n"
                     "   projCoords = gl_Position;\n"
                     "}\n"
                     "\n";
