#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

printExecutionTime()
{
    TIME_1=$(date +%s)
    TIME_T=$(expr $TIME_1 - $2)
    TIME_H=$(expr $TIME_T / 3600)
    TIME_M=$(expr $(expr $TIME_T - 3600 \* $TIME_H) / 60)
    TIME_S=$(expr $TIME_T - 3600 \* $TIME_H - 60 \* $TIME_M)
    TIME_F=`printf %02d ${TIME_H}`:`printf %02d ${TIME_M}`:`printf %02d ${TIME_S}`
    echo "$1 $TIME_F $3 $4"
}

runApplicationAndPrintExecutionTime()
{
    TIME_TMP_0=$(date +%s)
    runApplication $@
    EXIT_CODE=$?
    printExecutionTime "$1 finished in" $TIME_TMP_0 "with exit code" $EXIT_CODE
    if [ $EXIT_CODE -ne 0 ]; then
        printExecutionTime "OpenFOAM finished with errors in" $TIME_0
        exit $EXIT_CODE;
    fi
}

runParallelAndPrintExecutionTime()
{
    TIME_TMP_0=$(date +%s)
    runParallel $@
    EXIT_CODE=$?
    printExecutionTime "$1 finished in" $TIME_TMP_0 "with exit code" $EXIT_CODE
    if [ $EXIT_CODE -ne 0 ]; then
        printExecutionTime "OpenFOAM finished with errors in" $TIME_0
        exit $EXIT_CODE;
    fi
}

#------------------------------------------------------------------------------

PARALLEL=true

TIME_0=$(date +%s)
echo $(date +%Y-%m-%d\ %H:%M:%S) - execution started...

touch open.foam

#------------------------------------------------------------------------------

runApplicationAndPrintExecutionTime blockMesh
runApplicationAndPrintExecutionTime surfaceFeatureExtract

if $PARALLEL
then
    runApplicationAndPrintExecutionTime decomposePar -copyZero
    runParallelAndPrintExecutionTime snappyHexMesh -overwrite
else
    runApplicationAndPrintExecutionTime snappyHexMesh -overwrite
fi

if $PARALLEL
then
    restore0Dir -processor
    runParallelAndPrintExecutionTime checkMesh
    runParallelAndPrintExecutionTime renumberMesh -parallel -overwrite
    runParallelAndPrintExecutionTime patchSummary -parallel
    runParallelAndPrintExecutionTime potentialFoam -parallel
    runParallelAndPrintExecutionTime $(getApplication) -parallel
    runApplicationAndPrintExecutionTime reconstructParMesh -constant
    runApplicationAndPrintExecutionTime reconstructPar -latestTime
else
    restore0Dir
    runApplicationAndPrintExecutionTime checkMesh
    runApplicationAndPrintExecutionTime potentialFoam
    runApplicationAndPrintExecutionTime $(getApplication)
fi

echo "Running foamLog on $(pwd)"
foamLog log.$(getApplication)

#------------------------------------------------------------------------------

echo $(date +%Y-%m-%d\ %H:%M:%S) - execution finished.
printExecutionTime "OpenFOAM finished in" $TIME_0
