char shader_frag[] = "uniform sampler2D sceneTex;\n"
                     "uniform sampler2D noiseTex;\n"
                     "uniform float osg_FrameTime;\n"
                     "\n"
                     "void main()\n"
                     "{\n"
                     "   float factor = osg_FrameTime * 100.0;\n"
                     "   vec2 uv = vec2(0.4*sin(factor), 0.4*cos(factor));\n"
                     "   vec3 n = texture2D(noiseTex, (gl_TexCoord[0].st*3.5) + uv).rgb;\n"
                     "\n"
                     "   vec3 c = texture2D(sceneTex, gl_TexCoord[0].st + (n.xy*0.005)).rgb;\n"
                     "   float lum = dot(vec3(0.30, 0.59, 0.11), c);\n"
                     "   if (lum < 0.2) c *= 4.0;\n"
                     "\n"
                     "   vec3 finalColor = (c + (n*0.2)) * vec3(0.1, 0.95, 0.2);\n"
                     "   gl_FragColor = vec4(finalColor, 1.0);\n"
                     "}\n"
                     "\n";
