# https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/manage-windows-dockerfile
# Sample Dockerfile

# Indicates that the windowsservercore image will be used as the base image.
FROM mcr.microsoft.com/windows:ltsc2019

# Metadata indicating an image maintainer.
LABEL maintainer="jshelton@contoso.com"



# Sets a command or process that will run each time a container is run from the new image.
CMD [ "cmd" ]