#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

printExecutionTime()
{
    TIME_1=$(date +%s)
    TIME_T=$(expr $TIME_1 - $2)
    TIME_H=$(expr $TIME_T / 3600)
    TIME_M=$(expr $(expr $TIME_T - 3600 \* $TIME_H) / 60)
    TIME_S=$(expr $TIME_T - 3600 \* $TIME_H - 60 \* $TIME_M)
    TIME_F=`printf %02d ${TIME_H}`:`printf %02d ${TIME_M}`:`printf %02d ${TIME_S}`
    echo "$1 $TIME_F $3 $4"
}

runApplicationAndPrintExecutionTime()
{
    TIME_TMP_0=$(date +%s)
    runApplication $@
    EXIT_CODE=$?
    printExecutionTime "$1 finished in" $TIME_TMP_0 "with exit code" $EXIT_CODE
    if [ $EXIT_CODE -ne 0 ]; then exit $EXIT_CODE; fi
}

#------------------------------------------------------------------------------

TIME_0=$(date +%s)
echo $(date +%Y-%m-%d\ %H:%M:%S) - execution started...

touch open.foam

#------------------------------------------------------------------------------

runApplicationAndPrintExecutionTime blockMesh
runApplicationAndPrintExecutionTime checkMesh

#------------------------------------------------------------------------------

echo $(date +%Y-%m-%d\ %H:%M:%S) - execution finished.
printExecutionTime "OpenFOAM finished in" $TIME_0
